osx_image: xcode10.2
env:
  - SWIFT_VERSION=4.2
  - SWIFT_VERSION=5.0.1
language: generic
sudo: required
dist: trusty
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test
